In [10]:
import pandas as pd
import numpy as np
import pickle

In [2]:
df = pd.read_csv('/home/anuraaga/Documents/DataCodes/Projects/pricePredictor/dataset/dataset_bike/bikes.csv')

In [3]:
df

,model_name,model_year,kms_driven,owner,location,mileage,power,price
0,Bajaj Avenger Cruise 220 2017,2017,17000 Km,first owner,hyderabad,\n\n 35 kmpl,19 bhp,63500
1,Royal Enfield Classic 350cc 2016,2016,50000 Km,first owner,hyderabad,\n\n 35 kmpl,19.80 bhp,115000
2,Hyosung GT250R 2012,2012,14795 Km,first owner,hyderabad,\n\n 30 kmpl,28 bhp,300000
3,Bajaj Dominar 400 ABS 2017,2017,Mileage 28 Kms,first owner,pondicherry,\n\n 28 Kms,34.50 bhp,100000
4,Jawa Perak 330cc 2020,2020,2000 Km,first owner,bangalore,\n\n,30 bhp,197500
...,...,...,...,...,...,...,...,...
7852,Yamaha YZF-R15 150cc 2011,2011,7000 Km,first owner,agra,\n\n 42 kmpl,16 bhp,55000
7853,Bajaj Discover 100cc 2015,2015,Mileage 80 Kmpl,first owner,delhi,\n\n 80 Kmpl,7.7,28000
7854,Bajaj Pulsar 180cc 2016,2016,6407 Km,first owner,bangalore,\n\n 65 kmpl,17 bhp,61740
7855,Bajaj V15 150cc 2016,2016,7524 Km,first owner,bangalore,\n\n 57 kmpl,11.80 bhp,49000
7856,Bajaj Pulsar 220cc 2016,2016,15000 Km,first owner,chennai,\n\n 38 kmpl,21 bhp,65000

1. remove year from the end of model_name

In [6]:
def getBikeName(name):
    bikename = name.split()[:-1]
    return " ".join(bikename)

def getModelName(name):
    modelname = name.split()[0]
    return modelname

df['name'] = df['model_name'].apply(getBikeName)
df['model'] = df['model_name'].apply(getModelName)

In [8]:
df.drop('model_name', axis=1, inplace=True)

In [9]:
df

,model_year,kms_driven,owner,location,mileage,power,price,name,model
0,2017,17000 Km,first owner,hyderabad,\n\n 35 kmpl,19 bhp,63500,Bajaj Avenger Cruise 220,Bajaj
1,2016,50000 Km,first owner,hyderabad,\n\n 35 kmpl,19.80 bhp,115000,Royal Enfield Classic 350cc,Royal
2,2012,14795 Km,first owner,hyderabad,\n\n 30 kmpl,28 bhp,300000,Hyosung GT250R,Hyosung
3,2017,Mileage 28 Kms,first owner,pondicherry,\n\n 28 Kms,34.50 bhp,100000,Bajaj Dominar 400 ABS,Bajaj
4,2020,2000 Km,first owner,bangalore,\n\n,30 bhp,197500,Jawa Perak 330cc,Jawa
...,...,...,...,...,...,...,...,...,...
7852,2011,7000 Km,first owner,agra,\n\n 42 kmpl,16 bhp,55000,Yamaha YZF-R15 150cc,Yamaha
7853,2015,Mileage 80 Kmpl,first owner,delhi,\n\n 80 Kmpl,7.7,28000,Bajaj Discover 100cc,Bajaj
7854,2016,6407 Km,first owner,bangalore,\n\n 65 kmpl,17 bhp,61740,Bajaj Pulsar 180cc,Bajaj
7855,2016,7524 Km,first owner,bangalore,\n\n 57 kmpl,11.80 bhp,49000,Bajaj V15 150cc,Bajaj
7856,2016,15000 Km,first owner,chennai,\n\n 38 kmpl,21 bhp,65000,Bajaj Pulsar 220cc,Bajaj

In [11]:
pickle.dump(df, open('/home/anuraaga/Documents/DataCodes/Projects/pricePredictor/dataset/dataset_bike/bikes_v1.pkl', 'wb'))